"""Filter grasps for kinematic feasibility inside cluttered scenes.

For every scene generated by gen_clutter_scene.py and every object in it, the object's grasps
(e.g. the output of the 6-axis test, which contains 'stable_poses'/'stable_dofs') are placed in the
scene and rejected if the gripper
    - approaches from too low an angle,
    - moves the target object when spawned,
    - goes below the table (any link, or any sampled point of the gripper base mesh),
    - is part of a contact deeper than MAX_PENETRATION reported for a scene object (see the note below).
Grasps are evaluated in parallel over --num_workers cloned workstations.

Output: <output_dir>/<scene_id>-<gripper>-<object>-feasible_grasps.json with the input grasps and a
'result' list (1.0 = feasible, 0.0 = rejected).
"""
import os
import re
import gc
import sys
import json
import argparse
import numpy as np
from tqdm import tqdm
from pathlib import Path
from scipy.spatial.transform import Rotation as R
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from scene_utils import (load_grasps, calc_approach_angle_bot, import_gripper_with_physics,
                         get_matching_prim_paths, face_sampling_from_mesh, farthest_point_sampling)

# Filtering thresholds
MIN_APPROACH_ANGLE = 0.50       # rad, see calc_approach_angle_bot
MAX_OBJ_TRANSLATION = 0.005     # m, target object displacement after spawning the gripper
MAX_OBJ_ROTATION = 0.05         # rad
MIN_LINK_HEIGHT = 0.02          # m, lowest allowed gripper link origin
MIN_BASE_MESH_HEIGHT = 0.005    # m, lowest allowed point on the gripper base mesh
MAX_PENETRATION = -0.001        # m, contact separation below which a contact counts as a collision

def parse_args():
    parser = argparse.ArgumentParser(description="Generate feasible grasps for objects in a given scene")
    parser.add_argument("--scene_dir", type=str, default="./scenes", help="Directory containing scene folders (from gen_clutter_scene.py)")
    parser.add_argument("--gripper_dir", type=str, default="./grippers", help="Directory containing gripper files (USD)")
    parser.add_argument("--grasp_dir", type=str, default="./grasps", help="Directory containing grasp files, <grasp_dir>/<gripper>/<gripper>-<object>.json")
    parser.add_argument("--object_dir", type=str, default="./objects", help="Directory containing object files, <object_dir>/<object>/<object>.usd")
    parser.add_argument("--output_dir", type=str, default="./output", help="Directory to save feasible grasps")
    parser.add_argument("--gripper", type=str, required=True, help="Name of the gripper to use")
    parser.add_argument("--device", type=str, default="0", help="GPU to run the simulation on")
    parser.add_argument("--headless", action="store_true", help="Run in headless mode (no GUI)")
    parser.add_argument("--num_workers", type=int, default=20, help="Number of parallel workstations to use")
    return parser.parse_args()


if __name__=="__main__":
    args = parse_args()
    scene_dir = args.scene_dir
    gripper_dir = args.gripper_dir
    grasp_dir = args.grasp_dir
    object_dir = args.object_dir
    output_dir = args.output_dir
    gripper_name = args.gripper
    device = args.device
    num_workers = args.num_workers

    # Check for at least one scene in the scene dir
    scene_files = list(map(str, Path(scene_dir).rglob("*.json")))
    if len(scene_files) == 0:
        raise ValueError(f"No scene files found in {scene_dir}.")
    # Check if specified gripper usd file exists
    gripper_file = os.path.join(gripper_dir, f"{gripper_name}/{gripper_name}/{gripper_name}.usd")
    if not os.path.exists(gripper_file):
        raise ValueError(f"Gripper file {gripper_file} does not exist. Please check the gripper name.")

    ######################### Launch Isaac Sim #########################
    from omni.isaac.kit import SimulationApp
    config = {
        "headless": args.headless,
        "max_bounces": 0,
        "fast_shutdown": True,
        "max_specular_transmission_bounces": 0,
        "physics_gpu": device,
        "active_gpu": device,
        "multi_gpu": True
    }
    simulation_app = SimulationApp(config)

    # Omniverse imports
    from omni.isaac.core import World
    from omni.isaac.cloner import GridCloner
    import omni.isaac.core.utils.stage as stage_utils
    import omni.isaac.core.utils.prims as prim_utils
    from omni.isaac.core.utils.stage import add_reference_to_stage
    from omni.isaac.core.prims.geometry_prim import GeometryPrim, GeometryPrimView
    from omni.isaac.core.prims.rigid_prim import RigidPrimView
    from omni.isaac.core.articulations import ArticulationView
    from omni.isaac.core.utils.transformations import pose_from_tf_matrix, tf_matrices_from_poses, tf_matrix_from_pose
    from omni.physx import get_physx_simulation_interface
    from omni.physx.bindings._physx import ContactEventType
    from pxr import UsdGeom, PhysicsSchemaTools

    ######################### World Setup #########################
    with open(os.path.join(gripper_dir, "gripper_isaac_info.json")) as f:
        gripper_info = json.load(f)[gripper_name]

    base_mesh_vertices = None # Sampled points on the gripper base mesh (local frame), computed once
    world = None

    for scene_file in scene_files:
        print(f"\nLoading scene: {scene_file}")
        with open(scene_file, 'r') as f:
            scene_info = json.load(f)
        scene_id = Path(scene_file).stem

        # Clean up previous world before creating new one
        if world is not None:
            world.stop()
            world.clear()
            world = None
            gc.collect()

        # Create world
        stage_utils.create_new_stage()
        world = World(physics_dt=1/240.0, set_defaults=True)
        world.scene.add_default_ground_plane()
        world.reset()

        physicsContext = world.get_physics_context()
        physicsContext.set_solver_type("TGS")
        physicsContext.enable_gpu_dynamics(True)
        physicsContext.enable_stablization(True)
        world.reset()

        ######################### Setup workstations #########################
        # Add objects at their settled scene poses (camera entries are added by get_scene_rgbd.py)
        for obj in scene_info.keys():
            if "camera" in obj.lower():
                continue

            object_path = os.path.join(object_dir, obj, f"{obj}.usd")
            if not os.path.exists(object_path):
                raise ValueError(f"Object file {object_path} does not exist. Please check the object directory.")

            add_reference_to_stage(
                usd_path=os.path.abspath(object_path),
                prim_path=f"/World/workstation_0/objects/a_{obj}"
            )
            world.scene.add(
                GeometryPrim(
                    prim_path=f"/World/workstation_0/objects/a_{obj}",
                    name=obj,
                    position=scene_info[obj]["position"],
                    orientation=scene_info[obj]["orientation"],
                )
            )

        # Add gripper
        prim_utils.define_prim("/World/workstation_0/Robot")
        import_gripper_with_physics(world=world,
                                    work_path="/World/workstation_0/Robot",
                                    usd_path=gripper_file,
                                    EF_axis=gripper_info["EF_axis"])

        # Clone workstation
        cloner = GridCloner(spacing=2)
        target_paths = [f"/World/workstation_{i}" for i in range(num_workers)]
        cloner.clone(source_prim_path="/World/workstation_0", prim_paths=target_paths,
                     copy_from_source=True, replicate_physics=True, base_env_path="/World",
                     root_path="/World/workstation_")

        # Get views
        rigid_objs = world.scene.add(
            RigidPrimView(
                prim_paths_expr="/World/workstation_*/objects/*/base_link",
                track_contact_forces=True,
                prepare_contact_sensors=True,
                name=f"rigid_objs_{scene_file}",
            )
        )
        gripper_arts = world.scene.add(
            ArticulationView(
                prim_paths_expr="/World/workstation_*/Robot/gripper",
                reset_xform_properties=False,
                name="all_gripper_art_view",
            )
        )
        art_link_paths = get_matching_prim_paths(world, r"^\/World\/workstation_.*\/Robot\/gripper\/(?!.*root_joint)[^\/]+$")
        art_geo_view = world.scene.add(
            GeometryPrimView(
                prim_paths_expr=art_link_paths,
                name=f"all_links_geo_view",
            )
        )

        ######################### Load Grasp Poses #########################
        # Get all objects in the scene
        all_object_prim_paths = prim_utils.find_matching_prim_paths("/World/workstation_0/objects/*")
        all_object_names = [path.split("/")[-1][2:] for path in all_object_prim_paths]

        # Setup relevant prims for collision detection
        obj_collision_prims = ["/World/workstation_\\d*/Robot/gripper"]
        for object_name in all_object_names:
            obj_collision_prims.append(f"/World/workstation_\\d*/objects/a_{re.escape(object_name)}/base_link")

        # Iterate through objects
        for obj_idx, object_name in enumerate(all_object_names):
            output_file = os.path.join(output_dir, f"{scene_id}-{gripper_name}-{object_name}-feasible_grasps.json")
            if os.path.exists(output_file):
                print(f"Feasible grasps for {object_name} in {scene_id} already exist. Skipping...")
                continue
            print(f"\nProcessing object: {object_name} ({obj_idx+1}/{len(all_object_names)})")

            # Setup target object view
            target_object_view = world.scene.add(
                RigidPrimView(
                    prim_paths_expr=f"/World/workstation_*/objects/a_{object_name}/base_link",
                    name=f"target_{object_name}_view",
                )
            )

            # NOTE: Without a RigidPrimView for each of the other objects (plus re-initializing rigid_objs
            # after every reset), collisions between the gripper and non-target objects are missing from
            # the PhysX contact report. The views are not used otherwise, but must stay.
            for other_name in all_object_names:
                if other_name == object_name: continue
                world.scene.add(
                    RigidPrimView(
                        prim_paths_expr=f"/World/workstation_*/objects/a_{other_name}/base_link",
                        name=f"collision_view_{other_name}_{obj_idx}",
                    )
                )

            # Load grasps
            grasps = load_grasps(grasp_dir, gripper_name, object_name)
            if len(grasps["stable_poses"]) == 0:
                continue
            print(f"Loaded {len(grasps['stable_poses'])} grasps for {object_name}")

            results = {"object_id": object_name, "gripper_id": gripper_name, "scene_id": scene_id, "pose": [], "dofs": [], "stable_poses": [], "stable_dofs": [], "result": []}

            # Divide grasps among workers, rows of assignment_idxs are evaluated together (-1 = padding)
            init_poses = np.array(grasps["pose"])
            init_dofs = np.array(grasps["dofs"])
            stable_poses = np.array(grasps["stable_poses"])
            stable_dofs = np.array(grasps["stable_dofs"])
            grasps_per_worker = int(np.ceil(len(stable_poses) / num_workers))
            assignment_idxs = np.arange(grasps_per_worker * num_workers)
            assignment_idxs[assignment_idxs >= len(stable_poses)] = -1
            assignment_idxs = assignment_idxs.reshape((grasps_per_worker, num_workers))

            # Iterate through assigned grasps
            for j in tqdm(range(assignment_idxs.shape[0])):
                poses = stable_poses[assignment_idxs[j]]
                dofs = stable_dofs[assignment_idxs[j]]

                # Reset world and initialize new prims
                world.reset()
                rigid_objs.initialize(world.physics_sim_view)
                target_object_view.initialize(world.physics_sim_view)
                gripper_arts.initialize(world.physics_sim_view)
                art_geo_view.initialize(world.physics_sim_view)

                # Load gripper positions
                gripper_arts.set_joint_positions(dofs)

                # Orient grippers to grasp poses
                target_object_trans, target_object_rot = target_object_view.get_world_poses()
                target_object_T = tf_matrices_from_poses(target_object_trans, target_object_rot)
                grasp_T = tf_matrices_from_poses(poses[:, :3], poses[:, 3:])
                desired_gripper_tf = np.matmul(target_object_T, grasp_T).astype(float)

                num_grasps = len(desired_gripper_tf)
                desired_gripper_trans_arr = np.zeros((num_grasps, 3))
                desired_gripper_rot_arr = np.zeros((num_grasps, 4))
                for idx, tf in enumerate(desired_gripper_tf):
                    desired_gripper_trans_arr[idx], desired_gripper_rot_arr[idx] = pose_from_tf_matrix(tf)
                gripper_arts.set_world_poses(desired_gripper_trans_arr, desired_gripper_rot_arr)

                ######################### Perform filtering / collision detection #########################
                world.step()
                world.pause()
                grasp_good = np.array([True] * assignment_idxs.shape[1])

                # Filter by approach angle and object movement first
                new_object_trans, new_object_rot = target_object_view.get_world_poses()
                approach_angle = calc_approach_angle_bot(desired_gripper_trans_arr, new_object_trans)
                rel_pos = np.linalg.norm(target_object_trans - new_object_trans, axis=1)
                rel_rot_mtx = np.matmul(R.from_quat(np.roll(target_object_rot, -1, axis=1)).as_matrix().transpose(0, 2, 1),
                                        R.from_quat(np.roll(new_object_rot, -1, axis=1)).as_matrix())
                rel_rot = np.arccos(np.clip((np.trace(rel_rot_mtx, axis1=1, axis2=2) - 1) / 2, -1.0, 1.0))
                bad_mask = (approach_angle < MIN_APPROACH_ANGLE) | (rel_pos > MAX_OBJ_TRANSLATION) | (rel_rot > MAX_OBJ_ROTATION)
                grasp_good[bad_mask] = False

                # Filter by min z of gripper links
                all_link_trans = art_geo_view.get_world_poses()[0]
                links_below_z = all_link_trans[:, 2] < MIN_LINK_HEIGHT
                links_below_z = links_below_z.reshape(-1, len(all_link_trans) // num_workers)
                grasp_good[np.any(links_below_z, axis=1)] = False

                # Filter by min vertex on gripper base mesh
                bad_mask = []
                good_stations = np.where(grasp_good)[0]
                for station in good_stations:
                    base_mesh_prim_path = f"/World/workstation_{station}/Robot" + art_link_paths[0].split("/Robot")[1] + "/visuals/mesh_0"
                    base_mesh = UsdGeom.Mesh(world.stage.GetPrimAtPath(base_mesh_prim_path))
                    if base_mesh_vertices is None:
                        temp_vertices = np.array(base_mesh.GetPointsAttr().Get())
                        temp_face_vertex_counts = np.array(base_mesh.GetFaceVertexCountsAttr().Get())
                        temp_face_vertex_indices = np.array(base_mesh.GetFaceVertexIndicesAttr().Get())
                        temp_vertices = face_sampling_from_mesh(temp_vertices, temp_face_vertex_counts, temp_face_vertex_indices, num_samples=500)
                        temp_vertices = farthest_point_sampling(temp_vertices, 100)
                        base_mesh_vertices = np.array([tf_matrix_from_pose(np.array(v), np.array([0, 0, 0, 1])) for v in temp_vertices])
                    temp_vertices = base_mesh_vertices

                    temp_local_tf_matrix = np.array(base_mesh.GetLocalTransformation()).transpose()

                    art_geo_view_idx = art_link_paths.index(base_mesh_prim_path.split("/visuals/mesh_0")[0])
                    temp_world_tf_matrix = art_geo_view.get_world_poses()
                    temp_world_tf_matrix = tf_matrix_from_pose(temp_world_tf_matrix[0][art_geo_view_idx], temp_world_tf_matrix[1][art_geo_view_idx])

                    temp_vertices = np.matmul(temp_local_tf_matrix, temp_vertices)
                    temp_vertices = np.matmul(temp_world_tf_matrix, temp_vertices)
                    temp_vertices = np.array([pose_from_tf_matrix(v)[0] for v in temp_vertices])

                    bad_mask.append(np.min(temp_vertices[:, 2]) < MIN_BASE_MESH_HEIGHT)
                bad_mask = np.array(bad_mask, dtype=bool)
                grasp_good[good_stations[bad_mask]] = False

                # Filter by collision detection
                bad_actors = []
                contact_headers, contact_data, friction_anchors = get_physx_simulation_interface().get_full_contact_report()
                for contact_header in contact_headers:
                    if contact_header.type == ContactEventType.CONTACT_LOST or contact_header.num_contact_data == 0:
                        continue

                    contact_data_offset = contact_header.contact_data_offset
                    num_contact_data = contact_header.num_contact_data
                    separation = np.array([contact_data[k].separation for k in range(contact_data_offset, contact_data_offset + num_contact_data)])

                    actor0 = str(PhysicsSchemaTools.intToSdfPath(contact_header.actor0))
                    actor1 = str(PhysicsSchemaTools.intToSdfPath(contact_header.actor1))
                    actor0_relevant = any(re.search(pattern, actor0) for pattern in obj_collision_prims)
                    actor1_relevant = any(re.search(pattern, actor1) for pattern in obj_collision_prims)
                    if (actor0_relevant or actor1_relevant) and (np.min(separation) < MAX_PENETRATION):
                        bad_actors.append(actor0 if actor0_relevant else actor1)
                bad_workstations = [int(id) for a in bad_actors for id in re.findall(r"/World/workstation_(\d+)", a)]
                grasp_good[bad_workstations] = False
                del contact_headers, contact_data, friction_anchors

                # Save feasible grasps to results
                remainder_mask = assignment_idxs[j] != -1
                truncated_ass_idx = assignment_idxs[j][remainder_mask]
                grasp_good = grasp_good[remainder_mask]
                results["pose"].extend(init_poses[truncated_ass_idx].tolist())
                results["dofs"].extend(init_dofs[truncated_ass_idx].tolist())
                results["stable_poses"].extend(stable_poses[truncated_ass_idx].tolist())
                results["stable_dofs"].extend(stable_dofs[truncated_ass_idx].tolist())
                results["result"].extend(grasp_good.astype(float).tolist())

                # Periodic garbage collection to keep memory usage flat on long runs
                if j % 10 == 0:
                    gc.collect()

            # Save results to json
            os.makedirs(output_dir, exist_ok=True)
            with open(output_file, "w") as f:
                json.dump(results, f, indent=4)

            del results, init_poses, init_dofs, stable_poses, stable_dofs, assignment_idxs, grasps
            target_object_view = None
            gc.collect()

    ######################### Clean Up #########################
    if world is not None:
        world.stop()
        world.clear()
    simulation_app.close()
